# Generated by Django 5.1.6 on 2025-02-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
